/*
 * fox11_lcdPanel.java
 *
 * Created on January 2, 2007, 3:51 PM
 * @author  Paul Kratt
 */

package hc11emulator;

import java.awt.Font;
import java.awt.Graphics;

public class fox11_lcdPanel extends javax.swing.JPanel {
    public byte[][] line = new byte[2][16];
    
    /** Creates new form fox11_lcdPanel */
    public fox11_lcdPanel() {
        initComponents();
        line[0][0] = 'E'; line[0][1] = 'M'; line[0][2] = 'U';
        line[0][3] = 'L'; line[0][4] = 'A'; line[0][5] = 'T';
        line[0][6] = 'O'; line[0][7] = 'R'; line[0][8] = ' ';
        line[0][9] = 'L'; line[0][10] = 'C'; line[0][11] = 'D';
        line[0][12] = ' '; line[0][13] = ' '; line[0][14] = ' '; line[0][15] = ' ';
        
        line[1][0] = 'R'; line[1][1] = 'e'; line[1][2] = 'a';
        line[1][3] = 'd'; line[1][4] = 'y'; line[1][5] = ' ';
        line[1][6] = ' '; line[1][7] = ' '; line[1][8] = ' ';
        line[1][9] = 'V'; line[1][10] = 'e'; line[1][11] = 'r';
        line[1][12] = ':'; line[1][13] = '1'; line[1][14] = '.'; line[1][15] = '0';
    }

    public void paint(Graphics g) {
        super.paint(g);
        int fontsize = (this.getHeight()-this.getY())/2;
        
        g.setFont(new Font("Courier New",Font.PLAIN,fontsize));
        g.drawBytes(line[0],0,16,10,this.getY()+fontsize/2);
        g.drawBytes(line[1],0,16,10,this.getY()+(fontsize*3)/2);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        setLayout(null);

    }// </editor-fold>//GEN-END:initComponents
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
    
}
