/*
 * fox11_LED_DIPSwin.java
 *
 * Created on July 7, 2006, 9:52 PM
 *
 *@author Paul Kratt
 */

package hc11emulator;

public class fox11_LED_DIPSwin extends javax.swing.JFrame implements hc11_Observer {
    hc11_Device localboard; //We keep a local copy of the board for easy destroying
    
    /** Creates new form fox11_LED_DIPSwin */
    public fox11_LED_DIPSwin(hc11_Device localboard) {
        initComponents();
        this.localboard=localboard;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        jLabel1 = new javax.swing.JLabel();
        lblLEDS = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("FOX11 LED's and DIP switches");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("These are LEDS: (TO DO: Use a picture.)");

        lblLEDS.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLEDS.setText("00000000");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("These are DIP switches: (TO DO: Add them)");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(lblLEDS, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(lblLEDS)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2)
                .addContainerGap(225, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        localboard.removeObserver(this); //Remove ourselves from the board, assuming something added us.
        //Won't do anything otherwise, which is good.
    }//GEN-LAST:event_formWindowClosing

    /** This function is called by the device when it wants the window to update. */
    public void visualUpdate() {
        String display = Integer.toBinaryString(localboard.getMem(0x1404));
        
        while(display.length() < 8)
            display = "0" + display;
        lblLEDS.setText(display);
    }
    
    /** Return the name of this device. */
    public String getName(){
        return new String("FOX11 LED's and DIP switches");
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblLEDS;
    // End of variables declaration//GEN-END:variables
    
}
