/*
 * fox11_Keypad.java
 *
 * Created on January 3, 2007, 3:03 PM
 *
 * @author  Paul Kratt
 */

package hc11emulator;

import javax.swing.JOptionPane;

public class fox11_Keypad extends javax.swing.JFrame implements hc11_ramTrapper{
    private hc11_Device device; //The hc11 we're hooked up to.
    
    /** Creates new form fox11_Keypad */
    public fox11_Keypad(hc11_Device board) {
        initComponents();
        device = board;
        device.addTrap(0x1008,this); //It's a trap!
    }
    
    /**
     * Notify the class trapping this memory location that the trapped ram has been read from.
     *
     * @param trapaddr The address that was trapped
     * @param instaddr The address of the instruction that fell into our trap.
     */
    public void readTrap(int trapaddr, int instraddr) {
        //Don't care
    }
    
    /** Trap a write to here
     */
    public void writeTrap(int trapaddr, int instraddr) {
        //Keypad writes to 1008, reads from 100A
        int testval=device.getMemSilent(trapaddr);
        testval=(testval>>2)&0xF; //Shift it by two, since the pins aren't aligned.
        int retval=0xF;
        
        //1 - Nothing pressed, 0 - Something pressed
        //I'll use if statements here so we can simulate pressing more than one button at once!
        if((testval&0x1)==0){
            //0,4,8,C Column get signal!
            if(btn0.isSelected())
                retval&=14; //1110
            if(btn4.isSelected())
                retval&=13; //1101
            if(btn8.isSelected())
                retval&=11; //1011
            if(btnC.isSelected())
                retval&=7; //0111
        }
        if((testval&0x2)==0){
            //1,5,9,D Column get signal!
            if(btn1.isSelected())
                retval&=14; //1110
            if(btn5.isSelected())
                retval&=13; //1101
            if(btn9.isSelected())
                retval&=11; //1011
            if(btnD.isSelected())
                retval&=7; //0111
        }
        if((testval&0x4)==0){
            //2,6,A,E Column get signal!
            if(btn2.isSelected())
                retval&=14; //1110
            if(btn6.isSelected())
                retval&=13; //1101
            if(btnA.isSelected())
                retval&=11; //1011
            if(btnE.isSelected())
                retval&=7; //0111
        }
        if((testval&0x8)==0){
            //3,7,B,F Column get signal!
            if(btn3.isSelected())
                retval&=14; //1110
            if(btn7.isSelected())
                retval&=13; //1101
            if(btnB.isSelected())
                retval&=11; //1011
            if(btnF.isSelected())
                retval&=7; //0111
        }
        
        device.writeMemSilent(0x100A,retval);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {
        btn1 = new javax.swing.JToggleButton();
        btn2 = new javax.swing.JToggleButton();
        btn3 = new javax.swing.JToggleButton();
        btn4 = new javax.swing.JToggleButton();
        btn5 = new javax.swing.JToggleButton();
        btn6 = new javax.swing.JToggleButton();
        btn7 = new javax.swing.JToggleButton();
        btn8 = new javax.swing.JToggleButton();
        btn9 = new javax.swing.JToggleButton();
        btnA = new javax.swing.JToggleButton();
        btnB = new javax.swing.JToggleButton();
        btnC = new javax.swing.JToggleButton();
        btnD = new javax.swing.JToggleButton();
        btnE = new javax.swing.JToggleButton();
        btnF = new javax.swing.JToggleButton();
        btn0 = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Keypad");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        btn1.setText("1");

        btn2.setText("2");

        btn3.setText("3");

        btn4.setText("4");

        btn5.setText("5");

        btn6.setText("6");

        btn7.setText("7");

        btn8.setText("8");

        btn9.setText("9");

        btnA.setText("A");

        btnB.setText("B");

        btnC.setText("C");

        btnD.setText("D");

        btnE.setText("E");

        btnF.setText("F");

        btn0.setText("0");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(btnC)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnD)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnF))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(btn0, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(btn4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(btn8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(btn9)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(btnA)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(btnB))
                            .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                .add(layout.createSequentialGroup()
                                    .add(btn5)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(btn6)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(btn7))
                                .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                                    .add(btn1)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(btn2)
                                    .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                    .add(btn3))))))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(btn0)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btn4))
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(btn1)
                            .add(btn2)
                            .add(btn3))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(btn5)
                            .add(btn6)
                            .add(btn7))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btn8)
                    .add(btn9)
                    .add(btnA)
                    .add(btnB))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnC)
                    .add(btnD)
                    .add(btnE)
                    .add(btnF))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        device.removeTrap(this);
        System.out.println("Closed Keypad.");
    }//GEN-LAST:event_formWindowClosed
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn0;
    private javax.swing.JToggleButton btn1;
    private javax.swing.JToggleButton btn2;
    private javax.swing.JToggleButton btn3;
    private javax.swing.JToggleButton btn4;
    private javax.swing.JToggleButton btn5;
    private javax.swing.JToggleButton btn6;
    private javax.swing.JToggleButton btn7;
    private javax.swing.JToggleButton btn8;
    private javax.swing.JToggleButton btn9;
    private javax.swing.JToggleButton btnA;
    private javax.swing.JToggleButton btnB;
    private javax.swing.JToggleButton btnC;
    private javax.swing.JToggleButton btnD;
    private javax.swing.JToggleButton btnE;
    private javax.swing.JToggleButton btnF;
    // End of variables declaration//GEN-END:variables
    
}
